### ISSUE TITLE
About Table 2 BUTD+bal  accuracy from which datasets

### ISSUE THREAD

**Issue by alice-cool** [gqa-ood/GQA-OOD#1]
Dear scholar,
 I am glad to read your paper.
But I have questions about the result you showed in table 2 in the paper. 
![图片](https://user-images.githubusercontent.com/16870890/137105507-19229c81-e0e6-43f4-9b78-1d185dcf6a5e.png)

I think the result is too high about 60%, maybe from some datasets

In Lxmert, I found the BUTD method only gets at most 52%
![图片](https://user-images.githubusercontent.com/16870890/137105789-1f04df26-e1ff-4ffb-b0a6-1ed04c7502f9.png)

**Comment by CorentinKervadec** [comment]
Dear @alice-cool,

Thank you for your interest in our paper 😃 

The score difference is explained by the fact that the two tables are not using the same GQA split.
The scores in our Table 2 have been computed on the GQA validation split, while scores in Table 3 of LXMERT have been computed on the GQA testdev split.
